services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres #todo: use passwords from args? .env ?
      POSTGRES_USER: postgres
      POSTGRES_DB: flowers
    networks:
      - app
    # todo: add healthcheck
    # todo: add volume to local directory

  app:
    build: .
    restart: always
    ports:
      - "80:80"
    environment:
      # todo: use passwords from args? .env ?
      POSTGRES_DSN: "postgres://postgres:postgres@db:5432/flowers?sslmode=disable"
    networks:
      - app
    #todo: mount public directory
    #todo: check log drivers and logging options


networks:
  app:
    driver: bridge