services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: flowers
    networks:
      - app

  app:
    build: .
    restart: always
    ports:
      - "80:80"
    environment:
        POSTGRES_DSN: "postgres://postgres:postgres@db:5432/flowers?sslmode=disable"
    networks:
      - app

networks:
  app:
    driver: bridge