services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    volumes:
      - type: bind
        source: ./db-data
        target: /var/lib/postgresql/data

  app:
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - app
    logging:
      # Шось мені тут не ясно, шо має змінитись
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
networks:
  app:
    driver: bridge