version: '3'

tasks:
  build:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o app

  docker-run:
    cmds:
      - docker build -t flowers-app .
      - docker compose up db -d
      - docker run -e POSTGRES_DSN="postgres://postgres:postgres@host.docker.internal:5432/flowers?sslmode=disable"
          -p 80:80 flowers-app

  jenkins-run:
    cmds:
      - docker network create jenkins || true
      - docker run --name jenkins-docker --rm --detach 
        --privileged --network jenkins --network-alias docker 
        --env DOCKER_TLS_CERTDIR=/certs 
        --volume jenkins-docker-certs:/certs/client 
        --volume jenkins-data:/var/jenkins_home 
        --publish 2376:2376 
        docker:dind --storage-driver overlay2

      - docker build -t localjenkins -f Jenkins.Dockerfile .
      - docker run
        --name localjenkins
        --restart=on-failure
        --detach
        --network jenkins
        --env DOCKER_HOST=tcp://docker:2376
        --env DOCKER_CERT_PATH=/certs/client
        --env DOCKER_TLS_VERIFY=1
        --publish 8080:8080
        --publish 50000:50000
        --volume jenkins-data:/var/jenkins_home
        --volume jenkins-docker-certs:/certs/client:ro
        localjenkins

